name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - name: Main
        uses: lowlighter/metrics@latest
        if: ${{ success() || failure() }}
        with:
          filename: main.metrics.svg
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          # appearance mode
          base: header
          # begin plugins
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_details: lines, percentage
          plugin_languages_indepth: yes
          plugin_topics: yes
          plugins_topics_mode: mastered
          plugin_notable: yes
          plugin_notable_repositories: yes
          plugin_habits: yes
          config_order: base.header, isocalendar, languages, notable, habits, topics
          config_timezone: CST
      - name: Personal
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: personal.metrics.svg
          # Your GitHub token
          token: NOT_NEEDED
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: "GalaxySH"
          base: metadata
          plugin_music: yes
          plugin_music_provider: spotify # Use Spotify as provider
          plugin_music_mode: recent      # Set plugin mode
          plugin_music_limit: 4          # Limit to 4 entries
          plugin_music_played_at: yes    # Show timestamp (for spotify only)
          plugin_music_token: ${{ secrets.SPOTIFY_CLIENT_ID }}, ${{ secrets.SPOTIFY_CLIENT_SECRET }}, ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
